server:
    verbosity: 2
    interface: 192.168.10.2
    interface: 127.0.0.1
    port: 53
    
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # --- Access Control ---
    access-control: 192.168.10.0/24 allow
    access-control: 127.0.0.0/8 allow

    # --- Paths ---
    directory: "/users/hmt"
    username: ""     
    # username: "unbound"     
    do-daemonize: no
    chroot: ""       
    pidfile: "unbound.pid"
    logfile: ""     

    # --- DNSSEC ---
    module-config: "validator iterator"
    
    # trust-anchor: "com. 3600 IN DNSKEY ..."

# --- Stub Zone for .com ---
stub-zone:
    name: "com"
    stub-addr: 192.168.20.2
    # Force Unbound to use this server even if NS records say otherwise
    stub-prime: no
